site_name: Secretium Docs
site_url: https://docs.secretium.org/
repo_url: https://github.com/secretium/secretium
repo_name: secretium/secretium
edit_uri: main/docs

copyright: >-
  Copyright &copy; 2023 <a href="https://github.com/koddr" target="_blank">Vic Shóstak</a> and
  the <a href="https://github.com/truewebartisans" target="_blank">True Web Artisans</a> team.<br/>
  <a href="https://secretium.org" target="_blank">Secretium</a> is free and Open Source software licensed under the Apache 2.0 License.

nav:
  - About project: index.md
  - Quick start: quick-start/index.md
  - Complete user guide:
      - Introduction: complete-user-guide/index.md
      - How does it work?: complete-user-guide/how-does-it-work/index.md
      - Installation: complete-user-guide/installation/index.md
      - Configuration: complete-user-guide/configuration/index.md
      - Get SSL certificate: complete-user-guide/get-ssl-certificate/index.md
      - Configure proxy/web server: complete-user-guide/configure-proxy-web-server/index.md
  - FAQ: faq/index.md
  - Troubleshooting: troubleshooting/index.md
  - Get PRO version: get-pro/index.md

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png

  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye

  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.prune
    - navigation.footer
    - navigation.top
    - toc.follow
    - search.suggest
    - search.share

  font:
    text: Inter
    code: Fira Code

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - social
  - offline

extra:
  homepage: https://docs.secretium.org

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/secretium/secretium
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/secretium/secretium

  version:
    provider: mike
    default: latest

  # alternate:
  #   - name: English
  #     link: /en/
  #     lang: en
  #   - name: Русский
  #     link: /ru/
  #     lang: ru

  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - tables
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
